config/routes.rb
Rails.application.routes.draw do
  
  get  '/'           => 'home#index', as: :home  
  get  '/show'       => 'users#show'
  get  'signup'      => 'users#new'
  get  '/login'      => "sessions#new"
  post '/login'      => "sessions#create"
  get  '/logout'     => "sessions#destroy"
  get  '/post'       => 'gprequests#new'
  post '/post'       => 'gprequests#create'
  get  '/show_req'   => 'gprequests#show'
  get  '/list_req'   => 'gprequests#index'
  get  '/rank_req'   => 'gprequests#rank'
  get  '/user_vote'  => 'gprequests#user_vote'
  post '/user_vote'  => 'gprequests#user_vote'

  resources :users
  resources :gprequests do
    member do
      post "vote"
    end
  end
    
end

app/models/gprequest.rb
class Gprequest < ActiveRecord::Base
  belongs_to :user
  has_many :votes, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  
  has_many :gprequests, dependent: :destroy
  has_many :votes, dependent: :destroy

  before_save :downcase_email
  before_save :encrypt_password

  validates_confirmation_of :password
  validates :email, uniqueness: true

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :gprequest
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

helper_method :current_user

end

app/controllers/gprequests_controller.rb
class GprequestsController < ApplicationController

  def user_vote
    @gprequest = Gprequest.find(params[:id])
    @gprequest.votes << Vote.create(user: current_user)
    @gprequest.save
    redirect_to gprequests_path
  end

  def new
    @gprequest = Gprequest.new
  end

  def index
    @votecount = Vote.count
    @gprequests = Gprequest.all
    @allow_vote = true
    @vote_found = Vote.find_by(user_id: session[:user_id])
    if @vote_found
      @allow_vote = false 
    end
  end

  def show
    @gprequests = Gprequest.where(user_id: session[:user_id])
  end

  def create
    @gprequest = Gprequest.new(gprequest_params)
    if @gprequest.save
      flash[:success] = "Your request has been posted"
      redirect_to show_path
    else
      flash[:error] = "Your request did not post (confirm title entry)"
      redirect_to show_path
    end
  end

  def rank
    @gprequests = Gprequest.all
    rank_array = []     # an array of arrays
    @gprequests.each do |gprequest|
      rank_data = []
      vote_num = gprequest.votes.count
      rank_data = [gprequest.id, vote_num]
      rank_array << rank_data
    end
    @gprequest_rank = rank_array.sort do |a, b|
      b[1] <=> a[1]
    end
  end

  def vote_count
    vote_count = gprequest.votes.count
  end

  def destroy
  end

  private

  def gprequest_params
    params.require(:gprequest).permit(:id, :user_id, :title, :description)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      session[:email] = @user.email
      redirect_to show_path
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!  Please log in"
      redirect_to login_path
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to signup_path
    end
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end


  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController



  def vote_params
    params.require(:vote).permit(:request_id, :user_id)
  end

end
  

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/gprequests_helper.rb
module GprequestsHelper

  def vote_count(gprequest)
    vote_count = gprequest.votes.count
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/gprequests/index.html.erb
<%# app/views/gprequests/index.html.erb %>

<div class="container">
  <div class="view_req_page">
    <h3>
      OPEN REQUESTS
    </h3>
    <%= "Email: #{session[:email]} User ID: #{session[:user_id]}" %>
    <br></br>
    <% if @gprequests.count > 0 %>
      <% if @allow_vote %>
        <% @gprequests.each do | gprequest | %>
            <% vote_count = vote_count(gprequest) %>
        <tr>
          <td><%= "Request ID: #{gprequest.id}; " %>
          <td><%= "Title: '#{gprequest.title}'; " %></td>
          <td><%= "Description: '#{gprequest.description}' - " %></td>
          <td><%= "has #{vote_count} votes" %><td>
          <td><%=  button_to 'Vote for this request', user_vote_path(id: gprequest.id) %></td>    
        </tr>
        <% end %>
      <% end %>
      <% if !@allow_vote %>
        <%= "(You have already voted)" %>
        <% @gprequests.each do | gprequest | %>
          <p>
          <tr>
            <td><%= "Request ID: #{gprequest.id}; " %>
            <td><%= "Title: '#{gprequest.title}'; " %></td>
            <td><%= "Description: '#{gprequest.description}' - " %></td>
            <td><%= "has #{gprequest.votes.count} votes" %><td>    
          </tr>
          </p>
        <% end %>
      <% end %>
    <% else %>
      <%= "There are no open requests" %>
    <% end %>
  </div>
</div>

app/views/gprequests/new.html.erb
<!-- app/views/gprequests/new.html.erb -->

<div class="container">
  <div class="post_page">
    <h3>
      POST A NEW REQUEST
    </h3>
    <%= "Email: #{session[:email]} User ID: #{session[:user_id]}" %>
    <br></br>
    <%= form_for @gprequest do |f| %>
      <%= f.hidden_field :user_id, :value => session[:user_id] %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :description %>
      <%= f.text_field :description %>
      <%= f.submit "Post" %>
    <% end %>
  </div>
</div>

app/views/gprequests/rank.html.erb
<!-- app/views/gprequests/rank.html.erb -->

<div class="container">
  <div class="rank_page">
    <h3>
      REQUESTS RANKING BY VOTES
    </h3>
    <%= "Email: #{session[:email]} User ID: #{session[:user_id]}" %>
    <br></br>
    <% if @gprequests.count > 0 %>
      <% @gprequest_rank.each do |request| %>
        <% request_id = request[0] %>
        <% gprequest = Gprequest.find(request_id) %>
        <%= "(id:#{request_id}) | title:  '#{gprequest.title}' | descr:  '#{gprequest.description}' | votes: #{request[1]}" %>
        <br></br>
      <% end %>
    <% else %>
      <%= "There are no open requests" %>
    <% end %>
  </div>
</div>

app/views/gprequests/show.html.erb
<!-- app/views/gprequests/show.html.erb -->

<div class="container">
  <div class="your_req_page">
    <h3>
      YOUR REQUESTS
    </h3>
    <%= "Email: #{session[:email]} User ID: #{session[:user_id]}" %>
    <br></br>
    <% if @gprequests.count > 0 %>
      <% @gprequests.each do |gprequest| %>
        <p>
        <% vote_count = vote_count(gprequest) %>
        <%= "Request ID: #{gprequest.id}, title: '#{gprequest.title}', description: '#{gprequest.description}', (#{vote_count} votes)" %>
        </p>
      <% end %>
    <% else %>
      <%= "You have no open requests" %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb -->

<div class="container">
  <div class="home_page">
    <h3>
      <%= "WELCOME TO MEMBER REQUESTS" %>
    </h3>

    <div class="home_links">
      <%= link_to "Sign In", login_path %>
      <%= " or " %>
      <%= link_to "Sign Up", signup_path %>
    </div>
  </div>
</div>
  

app/views/layouts/application-prev0911.html.erb
<!-- app/views/layouts/application.html.erb -->

<!DOCTYPE html>
<html>
  <head>
   <title>The GP Request App</title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="utf-8">
  <title>Member Requests</title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href="css/stevewebdevfl.css" rel="stylesheet" type="text/css">
</head>
<body>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="js/bootstrap.js"></script>
  <div class="layout">
    <nav role="navigation" class="navbar navbar-inverse">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="#" class="navbar-brand">Member Requests</a>
        </div>
        <!-- Collection of nav links, forms, and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="hdrtext"><a href="/">Home</a></li>
            <li class="hdrtext"><a href=/show>Your Page</a></li>
            <li class="hdrtext"><a href=/post>Post Request</a></li>
            <li class="hdrtext"><a href=/show_req>Your Requests</a></li>
            <li class="hdrtext"><a href=/list_req>View Requests</a></li>
            <li class="hdrtext"><a href=/rank_req>Rank Requests</a></li>
            <li class="hdrtext"><a href=/login>Sign In</a></li>
            <li class="hdrtext"><a href=/signup>Sign Up</a></li>
          </ul>       
        </div>
      </div>
    </nav>
  </div>
<!DOCTYPE html>
<html>
  <head>
   
  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->

  <div class="container">
    <div class="signup_page">
      <h2>
        Sign Up
      </h2>

      <form class="form-inline">
          <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input type="text" class="form-control" id="password">
          </div>
          <div class="form-group">
            <label for="password">Confirm Password</label>
            <input type="text" class="form-control" id="password_confirmation">
          </div>
        
          <button type="submit" class="btn btn-default">Sign Up</button>
      </form>
    </div>
  </div>

  <!-- <div class="new_user">
    <%#=form_for User.new do |f| %>

      <%#=f.label :email %>
      <%#=f.text_field :email, :autofocus => true %>

     <%#=f.label :password %>
     <%#=f.password_field :password %>

     <%#=f.label :password_confirmation, "Confirm Password" %>
     <%#=f.password_field :password_confirmation %>

     <span id="sign_up">
       <%#=f.submit "Sign Up!" %>
     </span>

    <%# end %>
  </div> -->

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->

<div class="container">
  <div class="user_page">
    <h2>
      YOUR HOME PAGE
    </h2>
    <%= "Email: #{session[:email]} User ID: #{session[:user_id]}" %>
    <div id="flash_messages">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, :class => "flash #{key}") %>
      <% end %>
    </div>
  </div>
</div>

app/views/votes/show.html.erb
<!-- app/views/votes/show.html.erb